name: Sync data.json from source URL to repo (main)

on:
  schedule:
    - cron: '0 9,13,17 * * *' # 09:00, 13:00, 17:00 UTC daily
  workflow_dispatch:

permissions:
  contents: write

env:
  TARGET_FILE_PATH: data.json
  # Optional: set repo variable DATA_JSON_SOURCE_URL in Settings → Variables → Actions
  # If not set, workflow will fallback to GitHub Pages URL: https://<owner>.github.io/<repo>/data.json

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch remote data.json
        run: |
          SOURCE_URL="https://adminrhs.github.io/Dashboard/data.json"
          echo "Using source URL: $SOURCE_URL"
          curl -fL "$SOURCE_URL" -o /tmp/remote_data.json
          jq . /tmp/remote_data.json > /tmp/remote_pretty.json || {
            echo "Downloaded JSON is invalid"; exit 1; }

      - name: Compare with repo version
        id: diff
        run: |
          if [ ! -f "$TARGET_FILE_PATH" ]; then
            echo "missing=true" >> $GITHUB_OUTPUT
          elif ! diff -q /tmp/remote_pretty.json "$TARGET_FILE_PATH" >/dev/null 2>&1; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update file on main
        if: steps.diff.outputs.missing == 'true' || steps.diff.outputs.changed == 'true'
        run: |
          git fetch --all --prune
          DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
          git checkout "$DEFAULT_BRANCH"
          git pull --ff-only
          mv /tmp/remote_pretty.json "$TARGET_FILE_PATH"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$TARGET_FILE_PATH"
          git commit -m "chore(sync): update data.json from source URL"
          git push


