name: Sync data.json from source URL to repo

on:
  schedule:
    - cron: '0 9,13,17 * * *' # 09:00, 13:00, 17:00 UTC daily
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  TARGET_FILE_PATH: data.json
  SYNC_BRANCH: data-sync
  # Set this in repo Settings → Variables → Actions as DATA_JSON_SOURCE_URL
  # Alternatively replace with a hardcoded URL below

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate source URL variable
        run: |
          if [ -z "${{ vars.DATA_JSON_SOURCE_URL }}" ]; then
            echo "DATA_JSON_SOURCE_URL repo variable is not set. Configure it in Settings → Variables → Actions."
            exit 1
          fi

      - name: Fetch remote data.json
        run: |
          curl -fL "${{ vars.DATA_JSON_SOURCE_URL }}" -o /tmp/remote_data.json
          jq . /tmp/remote_data.json > /tmp/remote_pretty.json || {
            echo "Downloaded JSON is invalid"; exit 1; }

      - name: Compare with repo version
        id: diff
        run: |
          if [ ! -f "$TARGET_FILE_PATH" ]; then
            echo "missing=true" >> $GITHUB_OUTPUT
          elif ! diff -q /tmp/remote_pretty.json "$TARGET_FILE_PATH" >/dev/null 2>&1; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update file in sync branch
        if: steps.diff.outputs.missing == 'true' || steps.diff.outputs.changed == 'true'
        run: |
          git fetch --all --prune
          git checkout -B "$SYNC_BRANCH" || git switch -c "$SYNC_BRANCH"
          mv /tmp/remote_pretty.json "$TARGET_FILE_PATH"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$TARGET_FILE_PATH"
          git commit -m "chore(sync): update data.json from source URL"
          git push -u origin "$SYNC_BRANCH"

      - name: Create or update pull request
        if: steps.diff.outputs.missing == 'true' || steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(sync): update data.json from source URL"
          title: "Sync data.json from source URL"
          body: |
            This PR syncs `data.json` from `${{ vars.DATA_JSON_SOURCE_URL }}` into the repo.
          branch: ${{ env.SYNC_BRANCH }}
          base: ${{ github.event.repository.default_branch }}
          labels: sync, automation


