name: Update data.json via API

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Updated data.json content'
        required: true
        type: string
      commit_message:
        description: 'Commit message'
        required: false
        type: string
        default: 'Update data.json via API'

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update data.json
        run: |
          echo '${{ github.event.inputs.data }}' > data.json
          
          # Validate JSON
          jq . data.json > /dev/null || {
            echo "Invalid JSON provided"
            exit 1
          }

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add data.json
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push